name: Build Magisk module

on:
  workflow_dispatch:
  push:
    branches: [ "main", "master" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.event.head_commit.message, '[skip ci]') }}
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: 0

    - name: Extract info from update.json
      id: extract_info
      run: |
        VERSION=$(jq -r '.version' update.json)
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Setup Android NDK
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r27d-linux.zip
        unzip android-ndk-r27d-linux.zip
        
    - name: Build
      id: build
      run: |
        sudo apt-get update && sudo apt-get install -y zip jq
        chmod 777 ./build.sh
        ./build.sh
        mv out/magisk-module-release.zip out/magisk_overlayfs.zip
        
    - name: Upload release
      uses: actions/upload-artifact@v4
      with:
        name: magisk-overlayfs-release
        path: out/magisk_overlayfs.zip
        
    - name: Publish Release
      if: github.event_name == 'workflow_dispatch' || github.event_name == 'push'
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.VERSION }}
        name: "Release ${{ env.VERSION }}"
        files: out/magisk_overlayfs.zip
        body: |
          Magical OverlayFS Module ${{ env.VERSION }}
          Rewrite and bug fixed by SHAJON-404
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
